# Generated by Django 4.2.11 on 2024-04-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('invite_code', models.CharField(max_length=6, unique=True)),
                ('referral_code', models.CharField(max_length=6, unique=True)),
                ('used_count', models.IntegerField(default=0)),
                ('already_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to='InviteMaster.userprofile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='InviteMaster.userprofile')),
            ],
            options={
                'unique_together': {('referrer', 'referee')},
            },
        ),
    ]
