# Generated by Django 4.2.11 on 2024-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteMaster', '0002_alter_userprofile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='already_used',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
