# Generated by Django 4.2.11 on 2024-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteMaster', '0004_userprofile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='authorization_code',
            field=models.CharField(max_length=6),
        ),
    ]
