# Generated by Django 4.2.11 on 2024-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InviteMaster', '0005_alter_userprofile_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='authorization_code',
            field=models.CharField(max_length=4),
        ),
    ]
