# Generated by Django 4.2.11 on 2024-04-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InviteMaster', '0006_alter_userprofile_authorization_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
